
quarkus:
  http:
    host: 0.0.0.0

  datasource:
    db-kind: postgresql

  smallrye-jwt:
    enabled: true

  arc:
    fail-on-intercepted-private-method: false
    remove-unused-beans: false
    unremovable-types: "org.sky.util.jwt.JwtGenerator,org.sky.util.jwt.JwtValidator,org.sky.util.jwt.JwtExtractor"

# Custom JWT Configuration (común)
jwt:
  secret: "yapechamo-secret-key-2024-very-long-secret-key-for-jwt-signing"
  access-token:
    duration: "PT1H"
  refresh-token:
    duration: "PT24H"

# Application Configuration (común)
yapechamo:
  app:
    name: "YapeChamo"
    version: "1.0.0"

# WebSocket Configuration (común)
websocket:
  session:
    max-text-message-buffer-size: 4096
    max-idle-timeout: 60000